// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/proto/common.proto

package proto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container state and status
type ContainerStatus int32

const (
	ContainerStatus_CONTAINER_STATUS_UNSPECIFIED ContainerStatus = 0
	ContainerStatus_CONTAINER_STATUS_CREATED     ContainerStatus = 1
	ContainerStatus_CONTAINER_STATUS_RUNNING     ContainerStatus = 2
	ContainerStatus_CONTAINER_STATUS_PAUSED      ContainerStatus = 3
	ContainerStatus_CONTAINER_STATUS_RESTARTING  ContainerStatus = 4
	ContainerStatus_CONTAINER_STATUS_REMOVING    ContainerStatus = 5
	ContainerStatus_CONTAINER_STATUS_EXITED      ContainerStatus = 6
	ContainerStatus_CONTAINER_STATUS_DEAD        ContainerStatus = 7
)

// Enum value maps for ContainerStatus.
var (
	ContainerStatus_name = map[int32]string{
		0: "CONTAINER_STATUS_UNSPECIFIED",
		1: "CONTAINER_STATUS_CREATED",
		2: "CONTAINER_STATUS_RUNNING",
		3: "CONTAINER_STATUS_PAUSED",
		4: "CONTAINER_STATUS_RESTARTING",
		5: "CONTAINER_STATUS_REMOVING",
		6: "CONTAINER_STATUS_EXITED",
		7: "CONTAINER_STATUS_DEAD",
	}
	ContainerStatus_value = map[string]int32{
		"CONTAINER_STATUS_UNSPECIFIED": 0,
		"CONTAINER_STATUS_CREATED":     1,
		"CONTAINER_STATUS_RUNNING":     2,
		"CONTAINER_STATUS_PAUSED":      3,
		"CONTAINER_STATUS_RESTARTING":  4,
		"CONTAINER_STATUS_REMOVING":    5,
		"CONTAINER_STATUS_EXITED":      6,
		"CONTAINER_STATUS_DEAD":        7,
	}
)

func (x ContainerStatus) Enum() *ContainerStatus {
	p := new(ContainerStatus)
	*p = x
	return p
}

func (x ContainerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_proto_enumTypes[0].Descriptor()
}

func (ContainerStatus) Type() protoreflect.EnumType {
	return &file_api_proto_common_proto_enumTypes[0]
}

func (x ContainerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerStatus.Descriptor instead.
func (ContainerStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{0}
}

// Operation status for long-running operations
type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_PENDING     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_RUNNING     OperationStatus = 2
	OperationStatus_OPERATION_STATUS_COMPLETED   OperationStatus = 3
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 4
	OperationStatus_OPERATION_STATUS_CANCELLED   OperationStatus = 5
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_PENDING",
		2: "OPERATION_STATUS_RUNNING",
		3: "OPERATION_STATUS_COMPLETED",
		4: "OPERATION_STATUS_FAILED",
		5: "OPERATION_STATUS_CANCELLED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_PENDING":     1,
		"OPERATION_STATUS_RUNNING":     2,
		"OPERATION_STATUS_COMPLETED":   3,
		"OPERATION_STATUS_FAILED":      4,
		"OPERATION_STATUS_CANCELLED":   5,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_proto_enumTypes[1].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_api_proto_common_proto_enumTypes[1]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{1}
}

// Resource limits and constraints
type ResourceLimits struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MemoryBytes         int64                  `protobuf:"varint,1,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`                             // Memory limit in bytes
	MemorySwapBytes     int64                  `protobuf:"varint,2,opt,name=memory_swap_bytes,json=memorySwapBytes,proto3" json:"memory_swap_bytes,omitempty"`               // Memory + swap limit in bytes
	CpuQuota            float64                `protobuf:"fixed64,3,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`                                     // CPU quota (e.g., 1.5 for 150%)
	CpuPeriod           int64                  `protobuf:"varint,4,opt,name=cpu_period,json=cpuPeriod,proto3" json:"cpu_period,omitempty"`                                   // CPU period in microseconds
	CpuShares           int32                  `protobuf:"varint,5,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`                                   // CPU shares (relative weight)
	CpusetCpus          string                 `protobuf:"bytes,6,opt,name=cpuset_cpus,json=cpusetCpus,proto3" json:"cpuset_cpus,omitempty"`                                 // CPUs in which to allow execution
	CpusetMems          string                 `protobuf:"bytes,7,opt,name=cpuset_mems,json=cpusetMems,proto3" json:"cpuset_mems,omitempty"`                                 // Memory nodes in which to allow execution
	BlkioWeight         int64                  `protobuf:"varint,8,opt,name=blkio_weight,json=blkioWeight,proto3" json:"blkio_weight,omitempty"`                             // Block IO weight
	BlkioWeightDevice   []*BlkioDevice         `protobuf:"bytes,9,rep,name=blkio_weight_device,json=blkioWeightDevice,proto3" json:"blkio_weight_device,omitempty"`          // Per-device weight
	BlkioDeviceReadBps  []*BlkioDevice         `protobuf:"bytes,10,rep,name=blkio_device_read_bps,json=blkioDeviceReadBps,proto3" json:"blkio_device_read_bps,omitempty"`    // Per-device read rate
	BlkioDeviceWriteBps []*BlkioDevice         `protobuf:"bytes,11,rep,name=blkio_device_write_bps,json=blkioDeviceWriteBps,proto3" json:"blkio_device_write_bps,omitempty"` // Per-device write rate
	KernelMemory        int64                  `protobuf:"varint,12,opt,name=kernel_memory,json=kernelMemory,proto3" json:"kernel_memory,omitempty"`                         // Kernel memory limit (deprecated)
	MemoryReservation   int64                  `protobuf:"varint,13,opt,name=memory_reservation,json=memoryReservation,proto3" json:"memory_reservation,omitempty"`          // Memory soft limit
	MemorySwappiness    int32                  `protobuf:"varint,14,opt,name=memory_swappiness,json=memorySwappiness,proto3" json:"memory_swappiness,omitempty"`             // Memory swappiness (0-100)
	OomKillDisable      bool                   `protobuf:"varint,15,opt,name=oom_kill_disable,json=oomKillDisable,proto3" json:"oom_kill_disable,omitempty"`                 // Disable OOM killer
	PidsLimit           int32                  `protobuf:"varint,16,opt,name=pids_limit,json=pidsLimit,proto3" json:"pids_limit,omitempty"`                                  // PIDs limit
	Ulimits             []*UlimitSpec          `protobuf:"bytes,17,rep,name=ulimits,proto3" json:"ulimits,omitempty"`                                                        // Ulimit specifications
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_api_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLimits) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetMemorySwapBytes() int64 {
	if x != nil {
		return x.MemorySwapBytes
	}
	return 0
}

func (x *ResourceLimits) GetCpuQuota() float64 {
	if x != nil {
		return x.CpuQuota
	}
	return 0
}

func (x *ResourceLimits) GetCpuPeriod() int64 {
	if x != nil {
		return x.CpuPeriod
	}
	return 0
}

func (x *ResourceLimits) GetCpuShares() int32 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *ResourceLimits) GetCpusetCpus() string {
	if x != nil {
		return x.CpusetCpus
	}
	return ""
}

func (x *ResourceLimits) GetCpusetMems() string {
	if x != nil {
		return x.CpusetMems
	}
	return ""
}

func (x *ResourceLimits) GetBlkioWeight() int64 {
	if x != nil {
		return x.BlkioWeight
	}
	return 0
}

func (x *ResourceLimits) GetBlkioWeightDevice() []*BlkioDevice {
	if x != nil {
		return x.BlkioWeightDevice
	}
	return nil
}

func (x *ResourceLimits) GetBlkioDeviceReadBps() []*BlkioDevice {
	if x != nil {
		return x.BlkioDeviceReadBps
	}
	return nil
}

func (x *ResourceLimits) GetBlkioDeviceWriteBps() []*BlkioDevice {
	if x != nil {
		return x.BlkioDeviceWriteBps
	}
	return nil
}

func (x *ResourceLimits) GetKernelMemory() int64 {
	if x != nil {
		return x.KernelMemory
	}
	return 0
}

func (x *ResourceLimits) GetMemoryReservation() int64 {
	if x != nil {
		return x.MemoryReservation
	}
	return 0
}

func (x *ResourceLimits) GetMemorySwappiness() int32 {
	if x != nil {
		return x.MemorySwappiness
	}
	return 0
}

func (x *ResourceLimits) GetOomKillDisable() bool {
	if x != nil {
		return x.OomKillDisable
	}
	return false
}

func (x *ResourceLimits) GetPidsLimit() int32 {
	if x != nil {
		return x.PidsLimit
	}
	return 0
}

func (x *ResourceLimits) GetUlimits() []*UlimitSpec {
	if x != nil {
		return x.Ulimits
	}
	return nil
}

type BlkioDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`  // Device path
	Rate          int64                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"` // Rate limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlkioDevice) Reset() {
	*x = BlkioDevice{}
	mi := &file_api_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlkioDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlkioDevice) ProtoMessage() {}

func (x *BlkioDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlkioDevice.ProtoReflect.Descriptor instead.
func (*BlkioDevice) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *BlkioDevice) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BlkioDevice) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type UlimitSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`  // Ulimit name (e.g., "nofile", "nproc")
	Soft          int64                  `protobuf:"varint,2,opt,name=soft,proto3" json:"soft,omitempty"` // Soft limit
	Hard          int64                  `protobuf:"varint,3,opt,name=hard,proto3" json:"hard,omitempty"` // Hard limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UlimitSpec) Reset() {
	*x = UlimitSpec{}
	mi := &file_api_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UlimitSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UlimitSpec) ProtoMessage() {}

func (x *UlimitSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UlimitSpec.ProtoReflect.Descriptor instead.
func (*UlimitSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *UlimitSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UlimitSpec) GetSoft() int64 {
	if x != nil {
		return x.Soft
	}
	return 0
}

func (x *UlimitSpec) GetHard() int64 {
	if x != nil {
		return x.Hard
	}
	return 0
}

// Network configuration
type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`                                   // Network mode: "bridge", "host", "none", "container"
	Networks      []string               `protobuf:"bytes,2,rep,name=networks,proto3" json:"networks,omitempty"`                           // Network names to connect
	Ports         []*PortMapping         `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`                                 // Port mappings
	DnsServers    []string               `protobuf:"bytes,4,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`     // Custom DNS servers
	DnsSearch     []string               `protobuf:"bytes,5,rep,name=dns_search,json=dnsSearch,proto3" json:"dns_search,omitempty"`        // DNS search domains
	DnsOptions    []string               `protobuf:"bytes,6,rep,name=dns_options,json=dnsOptions,proto3" json:"dns_options,omitempty"`     // DNS options
	Hostname      string                 `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`                           // Container hostname
	Domainname    string                 `protobuf:"bytes,8,opt,name=domainname,proto3" json:"domainname,omitempty"`                       // Container domain name
	Ip            string                 `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip,omitempty"`                                       // IPv4 address
	Ip6           string                 `protobuf:"bytes,10,opt,name=ip6,proto3" json:"ip6,omitempty"`                                    // IPv6 address
	MacAddress    string                 `protobuf:"bytes,11,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`    // MAC address
	ExtraHosts    []string               `protobuf:"bytes,12,rep,name=extra_hosts,json=extraHosts,proto3" json:"extra_hosts,omitempty"`    // Extra hosts entries
	NetworkMode   string                 `protobuf:"bytes,13,opt,name=network_mode,json=networkMode,proto3" json:"network_mode,omitempty"` // Network mode details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_api_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *NetworkConfig) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *NetworkConfig) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *NetworkConfig) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *NetworkConfig) GetDnsSearch() []string {
	if x != nil {
		return x.DnsSearch
	}
	return nil
}

func (x *NetworkConfig) GetDnsOptions() []string {
	if x != nil {
		return x.DnsOptions
	}
	return nil
}

func (x *NetworkConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NetworkConfig) GetDomainname() string {
	if x != nil {
		return x.Domainname
	}
	return ""
}

func (x *NetworkConfig) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkConfig) GetIp6() string {
	if x != nil {
		return x.Ip6
	}
	return ""
}

func (x *NetworkConfig) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkConfig) GetExtraHosts() []string {
	if x != nil {
		return x.ExtraHosts
	}
	return nil
}

func (x *NetworkConfig) GetNetworkMode() string {
	if x != nil {
		return x.NetworkMode
	}
	return ""
}

type PortMapping struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HostIp           string                 `protobuf:"bytes,1,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`                                  // Host IP to bind to
	HostPort         int32                  `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`                           // Host port
	ContainerPort    int32                  `protobuf:"varint,3,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`            // Container port
	Protocol         string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`                                            // Protocol: "tcp", "udp", "sctp"
	HostPortEnd      int32                  `protobuf:"varint,5,opt,name=host_port_end,json=hostPortEnd,proto3" json:"host_port_end,omitempty"`                // End of host port range
	ContainerPortEnd int32                  `protobuf:"varint,6,opt,name=container_port_end,json=containerPortEnd,proto3" json:"container_port_end,omitempty"` // End of container port range
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_api_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *PortMapping) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *PortMapping) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortMapping) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortMapping) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PortMapping) GetHostPortEnd() int32 {
	if x != nil {
		return x.HostPortEnd
	}
	return 0
}

func (x *PortMapping) GetContainerPortEnd() int32 {
	if x != nil {
		return x.ContainerPortEnd
	}
	return 0
}

// Volume and mount configuration
type VolumeMount struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                                          // Source path (host) or volume name
	Destination     string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`                                // Destination path in container
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                              // Mount type: "bind", "volume", "tmpfs"
	ReadOnly        bool                   `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`                     // Read-only mount
	BindPropagation string                 `protobuf:"bytes,5,opt,name=bind_propagation,json=bindPropagation,proto3" json:"bind_propagation,omitempty"` // Bind propagation: "private", "rprivate", "shared", "rshared", "slave", "rslave"
	TmpfsMode       string                 `protobuf:"bytes,6,opt,name=tmpfs_mode,json=tmpfsMode,proto3" json:"tmpfs_mode,omitempty"`                   // Tmpfs mode for tmpfs mounts
	TmpfsSize       int64                  `protobuf:"varint,7,opt,name=tmpfs_size,json=tmpfsSize,proto3" json:"tmpfs_size,omitempty"`                  // Tmpfs size in bytes
	MountOptions    []string               `protobuf:"bytes,8,rep,name=mount_options,json=mountOptions,proto3" json:"mount_options,omitempty"`          // Additional mount options
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_api_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *VolumeMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VolumeMount) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *VolumeMount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *VolumeMount) GetBindPropagation() string {
	if x != nil {
		return x.BindPropagation
	}
	return ""
}

func (x *VolumeMount) GetTmpfsMode() string {
	if x != nil {
		return x.TmpfsMode
	}
	return ""
}

func (x *VolumeMount) GetTmpfsSize() int64 {
	if x != nil {
		return x.TmpfsSize
	}
	return 0
}

func (x *VolumeMount) GetMountOptions() []string {
	if x != nil {
		return x.MountOptions
	}
	return nil
}

// Security options
type SecurityOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	User            string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`                                                 // User specification (user:group)
	Groups          []string               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`                                             // Additional groups
	CapAdd          []string               `protobuf:"bytes,3,rep,name=cap_add,json=capAdd,proto3" json:"cap_add,omitempty"`                               // Capabilities to add
	CapDrop         []string               `protobuf:"bytes,4,rep,name=cap_drop,json=capDrop,proto3" json:"cap_drop,omitempty"`                            // Capabilities to drop
	Privileged      bool                   `protobuf:"varint,5,opt,name=privileged,proto3" json:"privileged,omitempty"`                                    // Run in privileged mode
	SecurityOpt     string                 `protobuf:"bytes,6,opt,name=security_opt,json=securityOpt,proto3" json:"security_opt,omitempty"`                // Security options (e.g., apparmor, selinux)
	SecurityOpts    []string               `protobuf:"bytes,7,rep,name=security_opts,json=securityOpts,proto3" json:"security_opts,omitempty"`             // Multiple security options
	NoNewPrivileges bool                   `protobuf:"varint,8,opt,name=no_new_privileges,json=noNewPrivileges,proto3" json:"no_new_privileges,omitempty"` // Prevent escalation
	UsernsMode      string                 `protobuf:"bytes,9,opt,name=userns_mode,json=usernsMode,proto3" json:"userns_mode,omitempty"`                   // User namespace mode
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecurityOptions) Reset() {
	*x = SecurityOptions{}
	mi := &file_api_proto_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityOptions) ProtoMessage() {}

func (x *SecurityOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityOptions.ProtoReflect.Descriptor instead.
func (*SecurityOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *SecurityOptions) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SecurityOptions) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *SecurityOptions) GetCapAdd() []string {
	if x != nil {
		return x.CapAdd
	}
	return nil
}

func (x *SecurityOptions) GetCapDrop() []string {
	if x != nil {
		return x.CapDrop
	}
	return nil
}

func (x *SecurityOptions) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

func (x *SecurityOptions) GetSecurityOpt() string {
	if x != nil {
		return x.SecurityOpt
	}
	return ""
}

func (x *SecurityOptions) GetSecurityOpts() []string {
	if x != nil {
		return x.SecurityOpts
	}
	return nil
}

func (x *SecurityOptions) GetNoNewPrivileges() bool {
	if x != nil {
		return x.NoNewPrivileges
	}
	return false
}

func (x *SecurityOptions) GetUsernsMode() string {
	if x != nil {
		return x.UsernsMode
	}
	return ""
}

// Image information
type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // Image ID
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`                                                                           // Image digest
	RepoTags      []string               `protobuf:"bytes,3,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`                                                       // Repository tags
	RepoDigests   []string               `protobuf:"bytes,4,rep,name=repo_digests,json=repoDigests,proto3" json:"repo_digests,omitempty"`                                              // Repository digests
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`                                                                              // Image size in bytes
	Created       *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`                                                                         // Creation time
	Architecture  string                 `protobuf:"bytes,7,opt,name=architecture,proto3" json:"architecture,omitempty"`                                                               // Architecture
	Os            string                 `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"`                                                                                   // Operating system
	Labels        map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Image labels
	Env           []string               `protobuf:"bytes,10,rep,name=env,proto3" json:"env,omitempty"`                                                                                // Environment variables
	Cmd           []string               `protobuf:"bytes,11,rep,name=cmd,proto3" json:"cmd,omitempty"`                                                                                // Default command
	Entrypoint    []string               `protobuf:"bytes,12,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`                                                                  // Entrypoint
	ExposedPorts  []string               `protobuf:"bytes,13,rep,name=exposed_ports,json=exposedPorts,proto3" json:"exposed_ports,omitempty"`                                          // Exposed ports
	Volumes       []string               `protobuf:"bytes,14,rep,name=volumes,proto3" json:"volumes,omitempty"`                                                                        // Volume mount points
	WorkingDir    string                 `protobuf:"bytes,15,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                                // Working directory
	User          string                 `protobuf:"bytes,16,opt,name=user,proto3" json:"user,omitempty"`                                                                              // Default user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_api_proto_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{7}
}

func (x *ImageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageInfo) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ImageInfo) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *ImageInfo) GetRepoDigests() []string {
	if x != nil {
		return x.RepoDigests
	}
	return nil
}

func (x *ImageInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageInfo) GetCreated() *timestamp.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *ImageInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *ImageInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ImageInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ImageInfo) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ImageInfo) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *ImageInfo) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *ImageInfo) GetExposedPorts() []string {
	if x != nil {
		return x.ExposedPorts
	}
	return nil
}

func (x *ImageInfo) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *ImageInfo) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ImageInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// Container information
type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                    // Container ID (full)
	ShortId       string                 `protobuf:"bytes,2,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`                                                           // Container ID (short)
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                                                // Container name
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`                                                                              // Image reference
	ImageId       string                 `protobuf:"bytes,5,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`                                                           // Image ID
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`                                                                        // Platform
	Status        ContainerStatus        `protobuf:"varint,7,opt,name=status,proto3,enum=nerdctl.v1.ContainerStatus" json:"status,omitempty"`                                           // Current status
	ExitCode      int32                  `protobuf:"varint,8,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`                                                       // Exit code (if exited)
	Created       *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=created,proto3" json:"created,omitempty"`                                                                          // Creation time
	Started       *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=started,proto3" json:"started,omitempty"`                                                                         // Start time
	Finished      *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=finished,proto3" json:"finished,omitempty"`                                                                       // Finish time
	Command       []string               `protobuf:"bytes,12,rep,name=command,proto3" json:"command,omitempty"`                                                                         // Command and args
	Labels        map[string]string      `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Container labels
	NetworkConfig *NetworkConfig         `protobuf:"bytes,14,opt,name=network_config,json=networkConfig,proto3" json:"network_config,omitempty"`                                        // Network configuration
	Mounts        []*VolumeMount         `protobuf:"bytes,15,rep,name=mounts,proto3" json:"mounts,omitempty"`                                                                           // Volume mounts
	Resources     *ResourceLimits        `protobuf:"bytes,16,opt,name=resources,proto3" json:"resources,omitempty"`                                                                     // Resource limits
	Security      *SecurityOptions       `protobuf:"bytes,17,opt,name=security,proto3" json:"security,omitempty"`                                                                       // Security options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_api_proto_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ContainerInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ContainerInfo) GetStatus() ContainerStatus {
	if x != nil {
		return x.Status
	}
	return ContainerStatus_CONTAINER_STATUS_UNSPECIFIED
}

func (x *ContainerInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerInfo) GetCreated() *timestamp.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *ContainerInfo) GetStarted() *timestamp.Timestamp {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *ContainerInfo) GetFinished() *timestamp.Timestamp {
	if x != nil {
		return x.Finished
	}
	return nil
}

func (x *ContainerInfo) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerInfo) GetNetworkConfig() *NetworkConfig {
	if x != nil {
		return x.NetworkConfig
	}
	return nil
}

func (x *ContainerInfo) GetMounts() []*VolumeMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ContainerInfo) GetResources() *ResourceLimits {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ContainerInfo) GetSecurity() *SecurityOptions {
	if x != nil {
		return x.Security
	}
	return nil
}

type OperationProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                                                  // Unique operation ID
	Status        OperationStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=nerdctl.v1.OperationStatus" json:"status,omitempty"`                                              // Operation status
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                             // Progress message
	Progress      float64                `protobuf:"fixed64,4,opt,name=progress,proto3" json:"progress,omitempty"`                                                                         // Progress percentage (0.0-1.0)
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                        // Last update time
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationProgress) Reset() {
	*x = OperationProgress{}
	mi := &file_api_proto_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationProgress) ProtoMessage() {}

func (x *OperationProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationProgress.ProtoReflect.Descriptor instead.
func (*OperationProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{9}
}

func (x *OperationProgress) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationProgress) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *OperationProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationProgress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *OperationProgress) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *OperationProgress) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Error details
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                                                                   // Error code
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                             // Error message
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`                                                                         // Component that generated error
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional context
	Suggestions   []string               `protobuf:"bytes,5,rep,name=suggestions,proto3" json:"suggestions,omitempty"`                                                                     // Suggested fixes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_api_proto_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ErrorDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ErrorDetail) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

// Health check configuration
type HealthCheck struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Test               []string               `protobuf:"bytes,1,rep,name=test,proto3" json:"test,omitempty"`                                                          // Health check command
	IntervalSeconds    int32                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`            // Check interval in seconds
	TimeoutSeconds     int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`               // Check timeout in seconds
	StartPeriodSeconds int32                  `protobuf:"varint,4,opt,name=start_period_seconds,json=startPeriodSeconds,proto3" json:"start_period_seconds,omitempty"` // Start period in seconds
	Retries            int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`                                                   // Number of retries
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_api_proto_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheck) GetTest() []string {
	if x != nil {
		return x.Test
	}
	return nil
}

func (x *HealthCheck) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheck) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheck) GetStartPeriodSeconds() int32 {
	if x != nil {
		return x.StartPeriodSeconds
	}
	return 0
}

func (x *HealthCheck) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

// Log configuration
type LogConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`                                                                             // Log driver
	Options       map[string]string      `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Log driver options
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogConfig) Reset() {
	*x = LogConfig{}
	mi := &file_api_proto_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConfig) ProtoMessage() {}

func (x *LogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConfig.ProtoReflect.Descriptor instead.
func (*LogConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{12}
}

func (x *LogConfig) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *LogConfig) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// Restart policy
type RestartPolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                       // Policy name: "no", "always", "unless-stopped", "on-failure"
	MaximumRetryCount int32                  `protobuf:"varint,2,opt,name=maximum_retry_count,json=maximumRetryCount,proto3" json:"maximum_retry_count,omitempty"` // Maximum retry count for "on-failure"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RestartPolicy) Reset() {
	*x = RestartPolicy{}
	mi := &file_api_proto_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartPolicy) ProtoMessage() {}

func (x *RestartPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartPolicy.ProtoReflect.Descriptor instead.
func (*RestartPolicy) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{13}
}

func (x *RestartPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestartPolicy) GetMaximumRetryCount() int32 {
	if x != nil {
		return x.MaximumRetryCount
	}
	return 0
}

// Platform specification
type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Architecture  string                 `protobuf:"bytes,1,opt,name=architecture,proto3" json:"architecture,omitempty"`            // CPU architecture
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`                                // Operating system
	Variant       string                 `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`                      // Architecture variant
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"` // OS version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_api_proto_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{14}
}

func (x *Platform) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Platform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Platform) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *Platform) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

// Registry authentication
type RegistryAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                                // Registry username
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                                // Registry password
	ServerAddress string                 `protobuf:"bytes,3,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"` // Registry server address
	IdentityToken string                 `protobuf:"bytes,4,opt,name=identity_token,json=identityToken,proto3" json:"identity_token,omitempty"` // Identity token
	RegistryToken string                 `protobuf:"bytes,5,opt,name=registry_token,json=registryToken,proto3" json:"registry_token,omitempty"` // Registry token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryAuth) Reset() {
	*x = RegistryAuth{}
	mi := &file_api_proto_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryAuth) ProtoMessage() {}

func (x *RegistryAuth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryAuth.ProtoReflect.Descriptor instead.
func (*RegistryAuth) Descriptor() ([]byte, []int) {
	return file_api_proto_common_proto_rawDescGZIP(), []int{15}
}

func (x *RegistryAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistryAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistryAuth) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *RegistryAuth) GetIdentityToken() string {
	if x != nil {
		return x.IdentityToken
	}
	return ""
}

func (x *RegistryAuth) GetRegistryToken() string {
	if x != nil {
		return x.RegistryToken
	}
	return ""
}

var File_api_proto_common_proto protoreflect.FileDescriptor

const file_api_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/common.proto\x12\n" +
	"nerdctl.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x05\n" +
	"\x0eResourceLimits\x12!\n" +
	"\fmemory_bytes\x18\x01 \x01(\x03R\vmemoryBytes\x12*\n" +
	"\x11memory_swap_bytes\x18\x02 \x01(\x03R\x0fmemorySwapBytes\x12\x1b\n" +
	"\tcpu_quota\x18\x03 \x01(\x01R\bcpuQuota\x12\x1d\n" +
	"\n" +
	"cpu_period\x18\x04 \x01(\x03R\tcpuPeriod\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\x05 \x01(\x05R\tcpuShares\x12\x1f\n" +
	"\vcpuset_cpus\x18\x06 \x01(\tR\n" +
	"cpusetCpus\x12\x1f\n" +
	"\vcpuset_mems\x18\a \x01(\tR\n" +
	"cpusetMems\x12!\n" +
	"\fblkio_weight\x18\b \x01(\x03R\vblkioWeight\x12G\n" +
	"\x13blkio_weight_device\x18\t \x03(\v2\x17.nerdctl.v1.BlkioDeviceR\x11blkioWeightDevice\x12J\n" +
	"\x15blkio_device_read_bps\x18\n" +
	" \x03(\v2\x17.nerdctl.v1.BlkioDeviceR\x12blkioDeviceReadBps\x12L\n" +
	"\x16blkio_device_write_bps\x18\v \x03(\v2\x17.nerdctl.v1.BlkioDeviceR\x13blkioDeviceWriteBps\x12#\n" +
	"\rkernel_memory\x18\f \x01(\x03R\fkernelMemory\x12-\n" +
	"\x12memory_reservation\x18\r \x01(\x03R\x11memoryReservation\x12+\n" +
	"\x11memory_swappiness\x18\x0e \x01(\x05R\x10memorySwappiness\x12(\n" +
	"\x10oom_kill_disable\x18\x0f \x01(\bR\x0eoomKillDisable\x12\x1d\n" +
	"\n" +
	"pids_limit\x18\x10 \x01(\x05R\tpidsLimit\x120\n" +
	"\aulimits\x18\x11 \x03(\v2\x16.nerdctl.v1.UlimitSpecR\aulimits\"5\n" +
	"\vBlkioDevice\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x03R\x04rate\"H\n" +
	"\n" +
	"UlimitSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04soft\x18\x02 \x01(\x03R\x04soft\x12\x12\n" +
	"\x04hard\x18\x03 \x01(\x03R\x04hard\"\x92\x03\n" +
	"\rNetworkConfig\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1a\n" +
	"\bnetworks\x18\x02 \x03(\tR\bnetworks\x12-\n" +
	"\x05ports\x18\x03 \x03(\v2\x17.nerdctl.v1.PortMappingR\x05ports\x12\x1f\n" +
	"\vdns_servers\x18\x04 \x03(\tR\n" +
	"dnsServers\x12\x1d\n" +
	"\n" +
	"dns_search\x18\x05 \x03(\tR\tdnsSearch\x12\x1f\n" +
	"\vdns_options\x18\x06 \x03(\tR\n" +
	"dnsOptions\x12\x1a\n" +
	"\bhostname\x18\a \x01(\tR\bhostname\x12\x1e\n" +
	"\n" +
	"domainname\x18\b \x01(\tR\n" +
	"domainname\x12\x0e\n" +
	"\x02ip\x18\t \x01(\tR\x02ip\x12\x10\n" +
	"\x03ip6\x18\n" +
	" \x01(\tR\x03ip6\x12\x1f\n" +
	"\vmac_address\x18\v \x01(\tR\n" +
	"macAddress\x12\x1f\n" +
	"\vextra_hosts\x18\f \x03(\tR\n" +
	"extraHosts\x12!\n" +
	"\fnetwork_mode\x18\r \x01(\tR\vnetworkMode\"\xd8\x01\n" +
	"\vPortMapping\x12\x17\n" +
	"\ahost_ip\x18\x01 \x01(\tR\x06hostIp\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\x05R\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x03 \x01(\x05R\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\"\n" +
	"\rhost_port_end\x18\x05 \x01(\x05R\vhostPortEnd\x12,\n" +
	"\x12container_port_end\x18\x06 \x01(\x05R\x10containerPortEnd\"\x86\x02\n" +
	"\vVolumeMount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\x12)\n" +
	"\x10bind_propagation\x18\x05 \x01(\tR\x0fbindPropagation\x12\x1d\n" +
	"\n" +
	"tmpfs_mode\x18\x06 \x01(\tR\ttmpfsMode\x12\x1d\n" +
	"\n" +
	"tmpfs_size\x18\a \x01(\x03R\ttmpfsSize\x12#\n" +
	"\rmount_options\x18\b \x03(\tR\fmountOptions\"\xa6\x02\n" +
	"\x0fSecurityOptions\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x16\n" +
	"\x06groups\x18\x02 \x03(\tR\x06groups\x12\x17\n" +
	"\acap_add\x18\x03 \x03(\tR\x06capAdd\x12\x19\n" +
	"\bcap_drop\x18\x04 \x03(\tR\acapDrop\x12\x1e\n" +
	"\n" +
	"privileged\x18\x05 \x01(\bR\n" +
	"privileged\x12!\n" +
	"\fsecurity_opt\x18\x06 \x01(\tR\vsecurityOpt\x12#\n" +
	"\rsecurity_opts\x18\a \x03(\tR\fsecurityOpts\x12*\n" +
	"\x11no_new_privileges\x18\b \x01(\bR\x0fnoNewPrivileges\x12\x1f\n" +
	"\vuserns_mode\x18\t \x01(\tR\n" +
	"usernsMode\"\x9f\x04\n" +
	"\tImageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x1b\n" +
	"\trepo_tags\x18\x03 \x03(\tR\brepoTags\x12!\n" +
	"\frepo_digests\x18\x04 \x03(\tR\vrepoDigests\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x124\n" +
	"\acreated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\"\n" +
	"\farchitecture\x18\a \x01(\tR\farchitecture\x12\x0e\n" +
	"\x02os\x18\b \x01(\tR\x02os\x129\n" +
	"\x06labels\x18\t \x03(\v2!.nerdctl.v1.ImageInfo.LabelsEntryR\x06labels\x12\x10\n" +
	"\x03env\x18\n" +
	" \x03(\tR\x03env\x12\x10\n" +
	"\x03cmd\x18\v \x03(\tR\x03cmd\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\f \x03(\tR\n" +
	"entrypoint\x12#\n" +
	"\rexposed_ports\x18\r \x03(\tR\fexposedPorts\x12\x18\n" +
	"\avolumes\x18\x0e \x03(\tR\avolumes\x12\x1f\n" +
	"\vworking_dir\x18\x0f \x01(\tR\n" +
	"workingDir\x12\x12\n" +
	"\x04user\x18\x10 \x01(\tR\x04user\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x06\n" +
	"\rContainerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bshort_id\x18\x02 \x01(\tR\ashortId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x19\n" +
	"\bimage_id\x18\x05 \x01(\tR\aimageId\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.nerdctl.v1.ContainerStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\b \x01(\x05R\bexitCode\x124\n" +
	"\acreated\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x124\n" +
	"\astarted\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\astarted\x126\n" +
	"\bfinished\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bfinished\x12\x18\n" +
	"\acommand\x18\f \x03(\tR\acommand\x12=\n" +
	"\x06labels\x18\r \x03(\v2%.nerdctl.v1.ContainerInfo.LabelsEntryR\x06labels\x12@\n" +
	"\x0enetwork_config\x18\x0e \x01(\v2\x19.nerdctl.v1.NetworkConfigR\rnetworkConfig\x12/\n" +
	"\x06mounts\x18\x0f \x03(\v2\x17.nerdctl.v1.VolumeMountR\x06mounts\x128\n" +
	"\tresources\x18\x10 \x01(\v2\x1a.nerdctl.v1.ResourceLimitsR\tresources\x127\n" +
	"\bsecurity\x18\x11 \x01(\v2\x1b.nerdctl.v1.SecurityOptionsR\bsecurity\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x02\n" +
	"\x11OperationProgress\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.nerdctl.v1.OperationStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x01R\bprogress\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.nerdctl.v1.OperationProgress.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12A\n" +
	"\bmetadata\x18\x04 \x03(\v2%.nerdctl.v1.ErrorDetail.MetadataEntryR\bmetadata\x12 \n" +
	"\vsuggestions\x18\x05 \x03(\tR\vsuggestions\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04test\x18\x01 \x03(\tR\x04test\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x120\n" +
	"\x14start_period_seconds\x18\x04 \x01(\x05R\x12startPeriodSeconds\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\"\x9d\x01\n" +
	"\tLogConfig\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12<\n" +
	"\aoptions\x18\x02 \x03(\v2\".nerdctl.v1.LogConfig.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\rRestartPolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x13maximum_retry_count\x18\x02 \x01(\x05R\x11maximumRetryCount\"w\n" +
	"\bPlatform\x12\"\n" +
	"\farchitecture\x18\x01 \x01(\tR\farchitecture\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x18\n" +
	"\avariant\x18\x03 \x01(\tR\avariant\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\"\xbb\x01\n" +
	"\fRegistryAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12%\n" +
	"\x0eserver_address\x18\x03 \x01(\tR\rserverAddress\x12%\n" +
	"\x0eidentity_token\x18\x04 \x01(\tR\ridentityToken\x12%\n" +
	"\x0eregistry_token\x18\x05 \x01(\tR\rregistryToken*\x84\x02\n" +
	"\x0fContainerStatus\x12 \n" +
	"\x1cCONTAINER_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONTAINER_STATUS_CREATED\x10\x01\x12\x1c\n" +
	"\x18CONTAINER_STATUS_RUNNING\x10\x02\x12\x1b\n" +
	"\x17CONTAINER_STATUS_PAUSED\x10\x03\x12\x1f\n" +
	"\x1bCONTAINER_STATUS_RESTARTING\x10\x04\x12\x1d\n" +
	"\x19CONTAINER_STATUS_REMOVING\x10\x05\x12\x1b\n" +
	"\x17CONTAINER_STATUS_EXITED\x10\x06\x12\x19\n" +
	"\x15CONTAINER_STATUS_DEAD\x10\a*\xcc\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18OPERATION_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aOPERATION_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x04\x12\x1e\n" +
	"\x1aOPERATION_STATUS_CANCELLED\x10\x05B5Z3github.com/containerd/nerdctl-grpc-server/api/protob\x06proto3"

var (
	file_api_proto_common_proto_rawDescOnce sync.Once
	file_api_proto_common_proto_rawDescData []byte
)

func file_api_proto_common_proto_rawDescGZIP() []byte {
	file_api_proto_common_proto_rawDescOnce.Do(func() {
		file_api_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_common_proto_rawDesc), len(file_api_proto_common_proto_rawDesc)))
	})
	return file_api_proto_common_proto_rawDescData
}

var file_api_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_common_proto_goTypes = []any{
	(ContainerStatus)(0),        // 0: nerdctl.v1.ContainerStatus
	(OperationStatus)(0),        // 1: nerdctl.v1.OperationStatus
	(*ResourceLimits)(nil),      // 2: nerdctl.v1.ResourceLimits
	(*BlkioDevice)(nil),         // 3: nerdctl.v1.BlkioDevice
	(*UlimitSpec)(nil),          // 4: nerdctl.v1.UlimitSpec
	(*NetworkConfig)(nil),       // 5: nerdctl.v1.NetworkConfig
	(*PortMapping)(nil),         // 6: nerdctl.v1.PortMapping
	(*VolumeMount)(nil),         // 7: nerdctl.v1.VolumeMount
	(*SecurityOptions)(nil),     // 8: nerdctl.v1.SecurityOptions
	(*ImageInfo)(nil),           // 9: nerdctl.v1.ImageInfo
	(*ContainerInfo)(nil),       // 10: nerdctl.v1.ContainerInfo
	(*OperationProgress)(nil),   // 11: nerdctl.v1.OperationProgress
	(*ErrorDetail)(nil),         // 12: nerdctl.v1.ErrorDetail
	(*HealthCheck)(nil),         // 13: nerdctl.v1.HealthCheck
	(*LogConfig)(nil),           // 14: nerdctl.v1.LogConfig
	(*RestartPolicy)(nil),       // 15: nerdctl.v1.RestartPolicy
	(*Platform)(nil),            // 16: nerdctl.v1.Platform
	(*RegistryAuth)(nil),        // 17: nerdctl.v1.RegistryAuth
	nil,                         // 18: nerdctl.v1.ImageInfo.LabelsEntry
	nil,                         // 19: nerdctl.v1.ContainerInfo.LabelsEntry
	nil,                         // 20: nerdctl.v1.OperationProgress.MetadataEntry
	nil,                         // 21: nerdctl.v1.ErrorDetail.MetadataEntry
	nil,                         // 22: nerdctl.v1.LogConfig.OptionsEntry
	(*timestamp.Timestamp)(nil), // 23: google.protobuf.Timestamp
}
var file_api_proto_common_proto_depIdxs = []int32{
	3,  // 0: nerdctl.v1.ResourceLimits.blkio_weight_device:type_name -> nerdctl.v1.BlkioDevice
	3,  // 1: nerdctl.v1.ResourceLimits.blkio_device_read_bps:type_name -> nerdctl.v1.BlkioDevice
	3,  // 2: nerdctl.v1.ResourceLimits.blkio_device_write_bps:type_name -> nerdctl.v1.BlkioDevice
	4,  // 3: nerdctl.v1.ResourceLimits.ulimits:type_name -> nerdctl.v1.UlimitSpec
	6,  // 4: nerdctl.v1.NetworkConfig.ports:type_name -> nerdctl.v1.PortMapping
	23, // 5: nerdctl.v1.ImageInfo.created:type_name -> google.protobuf.Timestamp
	18, // 6: nerdctl.v1.ImageInfo.labels:type_name -> nerdctl.v1.ImageInfo.LabelsEntry
	0,  // 7: nerdctl.v1.ContainerInfo.status:type_name -> nerdctl.v1.ContainerStatus
	23, // 8: nerdctl.v1.ContainerInfo.created:type_name -> google.protobuf.Timestamp
	23, // 9: nerdctl.v1.ContainerInfo.started:type_name -> google.protobuf.Timestamp
	23, // 10: nerdctl.v1.ContainerInfo.finished:type_name -> google.protobuf.Timestamp
	19, // 11: nerdctl.v1.ContainerInfo.labels:type_name -> nerdctl.v1.ContainerInfo.LabelsEntry
	5,  // 12: nerdctl.v1.ContainerInfo.network_config:type_name -> nerdctl.v1.NetworkConfig
	7,  // 13: nerdctl.v1.ContainerInfo.mounts:type_name -> nerdctl.v1.VolumeMount
	2,  // 14: nerdctl.v1.ContainerInfo.resources:type_name -> nerdctl.v1.ResourceLimits
	8,  // 15: nerdctl.v1.ContainerInfo.security:type_name -> nerdctl.v1.SecurityOptions
	1,  // 16: nerdctl.v1.OperationProgress.status:type_name -> nerdctl.v1.OperationStatus
	23, // 17: nerdctl.v1.OperationProgress.updated_at:type_name -> google.protobuf.Timestamp
	20, // 18: nerdctl.v1.OperationProgress.metadata:type_name -> nerdctl.v1.OperationProgress.MetadataEntry
	21, // 19: nerdctl.v1.ErrorDetail.metadata:type_name -> nerdctl.v1.ErrorDetail.MetadataEntry
	22, // 20: nerdctl.v1.LogConfig.options:type_name -> nerdctl.v1.LogConfig.OptionsEntry
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_proto_common_proto_init() }
func file_api_proto_common_proto_init() {
	if File_api_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_common_proto_rawDesc), len(file_api_proto_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_proto_goTypes,
		DependencyIndexes: file_api_proto_common_proto_depIdxs,
		EnumInfos:         file_api_proto_common_proto_enumTypes,
		MessageInfos:      file_api_proto_common_proto_msgTypes,
	}.Build()
	File_api_proto_common_proto = out.File
	file_api_proto_common_proto_goTypes = nil
	file_api_proto_common_proto_depIdxs = nil
}
