// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.12.4
// source: health/v1/health.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHealthCheck = "/health.v1.Health/Check"
const OperationHealthHeartbeat = "/health.v1.Health/Heartbeat"

type HealthHTTPServer interface {
	// Check Check health/heartbeat status
	Check(context.Context, *HealthRequest) (*HealthResponse, error)
	// Heartbeat Heartbeat endpoint
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

func RegisterHealthHTTPServer(s *http.Server, srv HealthHTTPServer) {
	r := s.Route("/")
	r.GET("/health", _Health_Check0_HTTP_Handler(srv))
	r.GET("/heartbeat", _Health_Heartbeat0_HTTP_Handler(srv))
}

func _Health_Check0_HTTP_Handler(srv HealthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Check(ctx, req.(*HealthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthResponse)
		return ctx.Result(200, reply)
	}
}

func _Health_Heartbeat0_HTTP_Handler(srv HealthHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HeartbeatRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthHeartbeat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Heartbeat(ctx, req.(*HeartbeatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HeartbeatResponse)
		return ctx.Result(200, reply)
	}
}

type HealthHTTPClient interface {
	Check(ctx context.Context, req *HealthRequest, opts ...http.CallOption) (rsp *HealthResponse, err error)
	Heartbeat(ctx context.Context, req *HeartbeatRequest, opts ...http.CallOption) (rsp *HeartbeatResponse, err error)
}

type HealthHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthHTTPClient(client *http.Client) HealthHTTPClient {
	return &HealthHTTPClientImpl{client}
}

func (c *HealthHTTPClientImpl) Check(ctx context.Context, in *HealthRequest, opts ...http.CallOption) (*HealthResponse, error) {
	var out HealthResponse
	pattern := "/health"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthCheck))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HealthHTTPClientImpl) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...http.CallOption) (*HeartbeatResponse, error) {
	var out HeartbeatResponse
	pattern := "/heartbeat"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthHeartbeat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
